### ISSUE TITLE
pd_ndi: can't load library

### ISSUE THREAD

**Issue by tepaze** [gogo2/pd-ndi#1]
Hi Gogo2,

First, thanks to share your work.

 I'm trying to use pd-ndi, but the lib won't load. I'm using :
Pure Data 0.50 64bit on W10x64
Gem 0.94 (D:\PureData\Externals\Gem)
NewTek NDI Runtime v4  (C:\Programmes\NewTek\NDI 4 Runtime\v4)

I do a copy of all the dll from the NDI Runtime in the pd externals folder of pd-ndi 
D:\PureData\Externals\pd-ndi
D:\PureData\Externals\pd-ndi\Processing.NDI.Lib.[...].dll

Startup Pref : Gem before pd-NDI

When i start pd, Gem lib is loaded successfully, but pd-ndi don't...
Gem Object are OK

I tried to compile, but my experience is on Linux. Wiwdows is more or less a stranger for me actually. So it don't compile.

Pd to NDI really interrest me, can you help me please ?

**Comment by gogo2** [comment]
Hi,

Thanks for interest in my project.

First of all, please make sure that directory in your externals path is pd_ndi, not pd-ndi.
Same thing with startup: first Gem, then pd_ndi (rather than pd-ndi, it has to be the same as .dll file name)

**Comment by tepaze** [comment]
Ok, it works.

I just add pd_ndi in the prefs path and remove an special caractere (space) from the foldername.

Thanks for the reply and your work
