### ISSUE TITLE
"Couldn't create" error

### ISSUE THREAD

**Issue by 60-hz** [gogo2/pd-ndi#2]
Hi, 
Tried in OSX 10.9.5
Pd 0.50.0
GEM: ver: 0.94.git v0.94
Couldn't create all objects.

/Users/raphael/Documents/Pd/externals/pd_ndi/pd_ndi.pd_darwin: dlopen(/Users/raphael/Documents/Pd/externals/pd_ndi/pd_ndi.pd_darwin, 10): Library not loaded: @rpath/libndi.3.dylib
  Referenced from: /Users/raphael/Documents/Pd/externals/pd_ndi/pd_ndi.pd_darwin
  Reason: image not found

**Comment by gogo2** [comment]
Hi,

What is your version of NDI SDK?
Last release was compiled against v3.x, newest NDI version is 4.0, if you use it - pd_ndi won't work.

I will provide builds for NDI 4 soon.
You can also compile pd_ndi by yourself.

**Comment by brandflake11** [comment]
Hello, sorry to hijack this, but it seems that maybe NDI has released another sdk version that is incompatible with your release of the external? I get this message with your latest released external on 64-bit Arch Linux with latest pd and gem version:

```
/pd_ndi/pd_ndi.pd_linux: libndi.so.4: cannot open shared object file: No such file or directory
/home/brandon/Documents/Pd/externals/pd_ndi/pd_ndi.pd_linux: libndi.so.4: cannot open shared object file: No such file or directory
pd_ndi: can't load library
```
The ndi-sdk that I downloaded is actually libndi.so.4.0.1. Would you be able to compile a release with this new ndi, if that is the case?

**Comment by gogo2** [comment]
Hi,

I don't have access to linux machine at the moment, but
 [latest release](https://github.com/gogo2/pd-ndi/releases/tag/0.5.1) is compiled against NDI SDK major release 4 and should also work with 4.0.1 if you create symlink libndi.so.4 -> libndi.so.4.0.1.
It is strange thet it wasn't made by installer script.
Please let me know if it doesn't work.

**Comment by brandflake11** [comment]
On my Linux machine, I had to recompile the external to get it to work with 4.0.1, and the symlink was there, it just would not load until I recompiled my own version. 

Are you able to compile a windows version by any chance?

**Comment by gogo2** [comment]
[Here](https://github.com/gogo2/pd-ndi/releases/tag/0.5.2) you can find builds with NDI SDK 4.1 (relesed and downloaded on 16 Nov)

**Comment by brandflake11** [comment]
Wow, thank you. Where can I donate money to you?
