### ISSUE TITLE
could you help me with installation?

### ISSUE THREAD

**Issue by simmit123456789** [gogo2/pd-ndi#4]
Hi
I'm using windows and am using the precompiled version. Not having any luck getting it to work. could you explain exactly what file you're referring to here and where it needs to go? 
'NDI library file must be visible for pd_ndi also after compilation. Easiest way to make it so is to copy it to the installation folder of pd_ndi'
Thanks in advance,

**Comment by gogo2** [comment]
Hi,
Are you still struggling with the installation process?
